In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/card_transdata.csv")
df.head()

distance_from_home  distance_from_last_transaction  \
0           57.877857                        0.311140   
1           10.829943                        0.175592   
2            5.091079                        0.805153   
3            2.247564                        5.600044   
4           44.190936                        0.566486   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                        1.945940              1.0        1.0   
1                        1.294219              1.0        0.0   
2                        0.427715              1.0        0.0   
3                        0.362663              1.0        1.0   
4                        2.222767              1.0        1.0   

   used_pin_number  online_order  fraud  
0              0.0           0.0    0.0  
1              0.0           0.0    0.0  
2              0.0           1.0    0.0  
3              0.0           1.0    0.0  
4              0.0           1.0    0.0

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column                          Non-Null Count    Dtype  
---  ------                          --------------    -----  
 0   distance_from_home              1000000 non-null  float64
 1   distance_from_last_transaction  1000000 non-null  float64
 2   ratio_to_median_purchase_price  1000000 non-null  float64
 3   repeat_retailer                 1000000 non-null  float64
 4   used_chip                       1000000 non-null  float64
 5   used_pin_number                 1000000 non-null  float64
 6   online_order                    1000000 non-null  float64
 7   fraud                           1000000 non-null  float64
dtypes: float64(8)
memory usage: 61.0 MB
None


In [ ]:
#Paso a factor la columna de clase
df['fraud'] = df['fraud'].astype('category')
print(df['fraud'].dtype)

category


In [ ]:
# Establecer la semilla para reproducibilidad
np.random.seed(30162)

In [ ]:
from sklearn.model_selection import train_test_split

# 'fraud' es la columna a predecir
X = df.drop(columns=['fraud'])  # Características
y = df['fraud']  # Variable objetivo

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
# Usamos stratify=y para mantener la misma proporción de clases en el conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=30162)

# Imprimir el número de filas en el conjunto de entrenamiento
print(len(X_train))


750000
<class 'pandas.core.frame.DataFrame'>
Int64Index: 750000 entries, 271767 to 169501
Data columns (total 7 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   distance_from_home              750000 non-null  float64
 1   distance_from_last_transaction  750000 non-null  float64
 2   ratio_to_median_purchase_price  750000 non-null  float64
 3   repeat_retailer                 750000 non-null  float64
 4   used_chip                       750000 non-null  float64
 5   used_pin_number                 750000 non-null  float64
 6   online_order                    750000 non-null  float64
dtypes: float64(7)
memory usage: 45.8 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 250000 entries, 200252 to 120691
Data columns (total 7 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   distance_from_home            

In [ ]:
print(X_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 750000 entries, 271767 to 169501
Data columns (total 7 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   distance_from_home              750000 non-null  float64
 1   distance_from_last_transaction  750000 non-null  float64
 2   ratio_to_median_purchase_price  750000 non-null  float64
 3   repeat_retailer                 750000 non-null  float64
 4   used_chip                       750000 non-null  float64
 5   used_pin_number                 750000 non-null  float64
 6   online_order                    750000 non-null  float64
dtypes: float64(7)
memory usage: 45.8 MB
None


In [ ]:
print(X_test.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250000 entries, 200252 to 120691
Data columns (total 7 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   distance_from_home              250000 non-null  float64
 1   distance_from_last_transaction  250000 non-null  float64
 2   ratio_to_median_purchase_price  250000 non-null  float64
 3   repeat_retailer                 250000 non-null  float64
 4   used_chip                       250000 non-null  float64
 5   used_pin_number                 250000 non-null  float64
 6   online_order                    250000 non-null  float64
dtypes: float64(7)
memory usage: 15.3 MB
None


# Algoritmo SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
# Establecer la semilla para reproducibilidad
np.random.seed(30162)

In [ ]:
# Crear y entrenar el modelo SVM
svm_model = SVC(kernel='rbf', C=10, gamma=0.01)
svm_model.fit(X_train, y_train)

SVC(C=10, gamma=0.01)

In [ ]:
y_pred = svm_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.995924


In [ ]:
from sklearn.metrics import confusion_matrix
# Calcular la matriz de confusión
cm = confusion_matrix(y_test, y_pred)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[227884    350]
 [   669  21097]]


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Calcular métricas de evaluación
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Imprimir métricas
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# Imprimir un informe completo que incluye estas métricas para cada clase
print("Informe de Clasificación:")
print(classification_report(y_test, y_pred))


Accuracy: 0.995924
Precision: 0.98368070126358
Recall: 0.9692639897087201
F1 Score: 0.9764191331312336
Informe de Clasificación:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    228234
         1.0       0.98      0.97      0.98     21766

    accuracy                           1.00    250000
   macro avg       0.99      0.98      0.99    250000
weighted avg       1.00      1.00      1.00    250000



In [ ]:
#Guardo el modelo
from joblib import dump

# Guardar el modelo entrenado
dump(svm_model, '/content/svmodel.joblib')

['/content/svmodel.joblib']

# Gradient Boosting

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import confusion_matrix

In [ ]:
# Definir las características y la variable objetivo para el conjunto de entrenamiento
X_trainGB = X_train[['distance_from_home', 'distance_from_last_transaction', 'ratio_to_median_purchase_price',
                     'repeat_retailer', 'used_chip', 'used_pin_number', 'online_order']]
y_trainGB = y_train

In [ ]:
# Definir la estrategia de validación cruzada
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=30162)

# Crear el modelo Gradient Boosting
boostModel = GradientBoostingClassifier(n_estimators=1000, random_state=30162)

# Entrenar el modelo Gradient Boosting
boostModel.fit(X_trainGB, y_trainGB)

GradientBoostingClassifier(n_estimators=1000, random_state=30162)

In [ ]:
# Realizar predicciones en el conjunto de prueba
y_pred_testGBo = boostModel.predict(X_test)

In [ ]:
# Calcular la matriz de confusión
cm = confusion_matrix(y_test, y_pred_testGBo)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[228234      0]
 [     2  21764]]


In [128]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Calcular métricas de evaluación
accuracy = accuracy_score(y_test, y_pred_testGBo)
precision = precision_score(y_test, y_pred_testGBo)
recall = recall_score(y_test, y_pred_testGBo)
f1 = f1_score(y_test, y_pred_testGBo)

# Imprimir métricas
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# imprimir un informe completo que incluye estas métricas para cada clase
print("Informe de Clasificación:")
print(classification_report(y_test, y_pred_testGBo))

Accuracy: 0.999992
Precision: 1.0
Recall: 0.9999081135716255
F1 Score: 0.9999540546749368
Informe de Clasificación:
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    228234
         1.0       1.00      1.00      1.00     21766

    accuracy                           1.00    250000
   macro avg       1.00      1.00      1.00    250000
weighted avg       1.00      1.00      1.00    250000



In [ ]:
#Guardo el modelo
from joblib import dump

# Guardar el modelo entrenado
dump(boostModel, '/content/GboostModel.joblib')

['/content/GboostModel.joblib']

# Naive-Bayes

In [ ]:
# Importar las bibliotecas necesarias
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [ ]:
# Separar las características (X) y la variable objetivo (y)
X_trainNB = X_train
y_trainNB = y_train

In [ ]:
m_naive = GaussianNB()
m_naive.fit(X_trainNB, y_trainNB)

GaussianNB()

In [ ]:
# Realizar predicciones en el conjunto de prueba
y_pred_testNB = m_naive.predict(X_test)

In [ ]:
# Calcular la matriz de confusión
cm = confusion_matrix(y_test, y_pred_testNB)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[224837   3397]
 [  8832  12934]]


In [129]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Calcular métricas de evaluación
accuracy = accuracy_score(y_test, y_pred_testNB)
precision = precision_score(y_test, y_pred_testNB)
recall = recall_score(y_test, y_pred_testNB)
f1 = f1_score(y_test, y_pred_testNB)

# Imprimir métricas
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# imprimir un informe completo que incluye estas métricas para cada clase
print("Informe de Clasificación:")
print(classification_report(y_test, y_pred_testNB))

Accuracy: 0.951084
Precision: 0.791990692547915
Recall: 0.5942295322980796
F1 Score: 0.6790035960836812
Informe de Clasificación:
              precision    recall  f1-score   support

         0.0       0.96      0.99      0.97    228234
         1.0       0.79      0.59      0.68     21766

    accuracy                           0.95    250000
   macro avg       0.88      0.79      0.83    250000
weighted avg       0.95      0.95      0.95    250000



In [ ]:
#Guardo el modelo
from joblib import dump

# Guardar el modelo entrenado
dump(m_naive, '/content/NBModel.joblib')

['/content/NBModel.joblib']

# EJECUCIÓN DE ALGORITMOS SOBRE EL DATASET ORIGINAL

In [ ]:
#Divido el dataset en 1000 subdatasets de 1000 registros

# Calcula el número de subdatasets
n_subdatasets = len(df) // 1000 + 1

# Divide el DataFrame en subdatasets
vChunks = [df[i * 1000 : (i + 1) * 1000] for i in range(n_subdatasets)]

# Asegúrate de que el último subdataset contenga todas las filas restantes
vChunks[-1] = df[(n_subdatasets - 1) * 1000 :]


In [ ]:
print(vChunks[0])

     distance_from_home  distance_from_last_transaction  \
0             57.877857                        0.311140   
1             10.829943                        0.175592   
2              5.091079                        0.805153   
3              2.247564                        5.600044   
4             44.190936                        0.566486   
..                  ...                             ...   
995            9.873417                        1.022586   
996          168.091704                        6.304360   
997           44.047622                        0.510298   
998            2.998418                        0.193681   
999           38.133449                        0.167059   

     ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                          1.945940              1.0        1.0   
1                          1.294219              1.0        0.0   
2                          0.427715              1.0        0.0   
3                      

In [ ]:
# Convertir todos los subdatasets a DataFrames
vChunks_datasets = [pd.DataFrame(subset) for subset in vChunks]

In [ ]:
vChunks_datasets[0]

distance_from_home  distance_from_last_transaction  \
0             57.877857                        0.311140   
1             10.829943                        0.175592   
2              5.091079                        0.805153   
3              2.247564                        5.600044   
4             44.190936                        0.566486   
..                  ...                             ...   
995            9.873417                        1.022586   
996          168.091704                        6.304360   
997           44.047622                        0.510298   
998            2.998418                        0.193681   
999           38.133449                        0.167059   

     ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                          1.945940              1.0        1.0   
1                          1.294219              1.0        0.0   
2                          0.427715              1.0        0.0   
3                          0.362663              1.0        1.0   
4                          2.222767              1.0        1.0   
..                              ...              ...        ...   
995                        0.346643              1.0        0.0   
996                        0.416833              1.0        1.0   
997                        0.624706              1.0        0.0   
998                        0.743416              1.0        1.0   
999                        3.965637              1.0        0.0   

     used_pin_number  online_order fraud  
0                0.0           0.0   0.0  
1                0.0           0.0   0.0  
2                0.0           1.0   0.0  
3                0.0           1.0   0.0  
4                0.0           1.0   0.0  
..               ...           ...   ...  
995              0.0           0.0   0.0  
996              0.0           0.0   0.0  
997              0.0           1.0   0.0  
998              0.0           1.0   0.0  
999              0.0           1.0   0.0  

[1000 rows x 8 columns]

In [ ]:
# Suponiendo que 'y_true_0' son las etiquetas verdaderas correspondientes al primer subdataset
y_true_0 = vChunks_datasets[0]['fraud']
print(y_true_0)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: fraud, Length: 1000, dtype: category
Categories (2, float64): [0.0, 1.0]


<ipython-input-91-c4bf46bba18d>:3: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  print(y_true_0)


Ejecucion del modelo SVN

In [ ]:
from joblib import load

# Cargar el modelo SVN
svm_model_cargado = load('/content/svmodel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_SVM = svm_model_cargado.predict(vChunks_datasets[0].drop(columns=['fraud']))

In [ ]:
# Calcular la precisión para el primer subdataset
accuracy = accuracy_score(y_true_0, y_pred_0_SVM)
print("Accuracy:", accuracy)

Accuracy: 0.997


In [ ]:
from sklearn.metrics import confusion_matrix
# Calcular la matriz de confusión
cm = confusion_matrix(y_true_0, y_pred_0_SVM)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[921   0]
 [  3  76]]


Ejecucion Modelo Gradient Boosting

In [ ]:
from joblib import load

# Cargar el modelo GBoosting
GBmodel_cargado = load('/content/GboostModel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_GB = GBmodel_cargado.predict(vChunks_datasets[0].drop(columns=['fraud']))

In [ ]:
# Calcular la precisión para el primer subdataset
accuracy = accuracy_score(y_true_0, y_pred_0_GB)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
# Calcular la matriz de confusión
cm = confusion_matrix(y_true_0, y_pred_0_GB)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[921   0]
 [  0  79]]


Ejecución del modelo Naive-Bayes

In [ ]:
from joblib import load

# Cargar el modelo GBoosting
NBmodel_cargado = load('/content/NBModel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_NB = NBmodel_cargado.predict(vChunks_datasets[0].drop(columns=['fraud']))

In [ ]:
# Calcular la precisión para el primer subdataset
accuracy = accuracy_score(y_true_0, y_pred_0_NB)
print("Accuracy:", accuracy)

Accuracy: 0.961


In [ ]:
from sklearn.metrics import confusion_matrix
# Calcular la matriz de confusión
cm = confusion_matrix(y_true_0, y_pred_0_NB)
print("Matriz de Confusión:")
print(cm)

Matriz de Confusión:
[[913   8]
 [ 31  48]]


Prediciones sobre registros cargados por el usuario

In [ ]:
#Creacion de registro custom
# Definir nombres de columnas y valores
namesDf = ["distance_from_home", "distance_from_last_transaction", "ratio_to_median_purchase_price",
           "repeat_retailer", "used_chip", "used_pin_number", "online_order"]
valoresDf = [57, 5, 2, 1, 0, 0, 1]

# Crear un DataFrame
Df_Analisis = pd.DataFrame([valoresDf], columns=namesDf)

# Mostrar el DataFrame
print(Df_Analisis)

   distance_from_home  distance_from_last_transaction  \
0                  57                               5   

   ratio_to_median_purchase_price  repeat_retailer  used_chip  \
0                               2                1          0   

   used_pin_number  online_order  
0                0             1  


SVN

In [ ]:
from joblib import load

# Cargar el modelo SVN
svm_model_cargado = load('/content/svmodel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_SVM_Custom = svm_model_cargado.predict(Df_Analisis)
print(y_pred_0_SVM_Custom)

[0.]


Gradient Boosting

In [ ]:
from joblib import load

# Cargar el modelo SVN
GB_model_cargado = load('/content/GboostModel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_GB_Custom = GB_model_cargado.predict(Df_Analisis)
print(y_pred_0_GB_Custom)

[0.]


Naive Bayes

In [ ]:
from joblib import load

# Cargar el modelo SVN
NB_model_cargado = load('/content/NBModel.joblib')

In [ ]:
# Calcular las predicciones del modelo para el primer subdataset
y_pred_0_NB_Custom = NB_model_cargado.predict(Df_Analisis)
print(y_pred_0_NB_Custom)

[0.]
